export interface Breed {
  id: string;
  name: string;
  hindiName: string;
  species: "Cattle" | "Buffalo";
  state: string;
  purpose: "Dairy" | "Draft" | "Dual Purpose";
  milkYield: string | null;
  bodyColor: string;
  hornType: string;
  size: string;
  conservationStatus: "Common" | "Vulnerable" | "Endangered";
  traits: string[];
  description: string;
}

export const breedsData: Breed[] = [
  {
    id: "gir",
    name: "Gir",
    hindiName: "गिर",
    species: "Cattle",
    state: "Gujarat",
    purpose: "Dairy",
    milkYield: "10-15 liters/day",
    bodyColor: "White with red or chocolate patches",
    hornType: "Long, curved backwards",
    size: "Large",
    conservationStatus: "Common",
    traits: ["High milk yield", "Heat tolerant", "Disease resistant"],
    description:
      "The Gir breed originates from the Gir forest region of Gujarat and is one of India's most popular dairy breeds. Known for its distinctive domed forehead and pendulous ears, it produces milk rich in A2 beta-casein protein. Widely exported to Brazil where it became highly productive.",
  },
  {
    id: "sahiwal",
    name: "Sahiwal",
    hindiName: "साहीवाल",
    species: "Cattle",
    state: "Punjab",
    purpose: "Dairy",
    milkYield: "8-12 liters/day",
    bodyColor: "Reddish-brown to mahogany",
    hornType: "Short, thick, blunt",
    size: "Medium-large",
    conservationStatus: "Common",
    traits: ["High fat milk", "Tick resistant", "Docile temperament"],
    description:
      "Sahiwal is considered India's best indigenous dairy breed, originating from Montgomery district (now in Pakistan) and Punjab. It produces milk with exceptionally high fat content (4-5%) and is highly valued for crossbreeding programs across tropical regions worldwide.",
  },
  {
    id: "tharparkar",
    name: "Tharparkar",
    hindiName: "थारपारकर",
    species: "Cattle",
    state: "Rajasthan",
    purpose: "Dual Purpose",
    milkYield: "5-8 liters/day",
    bodyColor: "White to grey",
    hornType: "Medium length, upward curving",
    size: "Medium",
    conservationStatus: "Common",
    traits: ["Drought hardy", "Desert adapted", "Good work capacity"],
    description:
      "Tharparkar cattle evolved in the harsh Thar desert of Rajasthan, developing exceptional drought resilience and ability to thrive on sparse vegetation. The breed serves dual purposes — providing both milk and draft power to farmers in arid regions.",
  },
  {
    id: "red-sindhi",
    name: "Red Sindhi",
    hindiName: "लाल सिंधी",
    species: "Cattle",
    state: "Rajasthan",
    purpose: "Dairy",
    milkYield: "6-10 liters/day",
    bodyColor: "Deep red",
    hornType: "Short, thick",
    size: "Medium",
    conservationStatus: "Vulnerable",
    traits: ["Heat tolerant", "High fat milk", "Hardy constitution"],
    description:
      "Originally from Sindh (present-day Pakistan), Red Sindhi cattle are prized for their adaptability to hot, humid conditions and resistance to tropical diseases. Their rich red coat and compact build make them easily identifiable. Widely distributed across South and Southeast Asia.",
  },
  {
    id: "kankrej",
    name: "Kankrej",
    hindiName: "कांकरेज",
    species: "Cattle",
    state: "Gujarat",
    purpose: "Draft",
    milkYield: "3-5 liters/day",
    bodyColor: "Silver grey to steel grey",
    hornType: "Lyre-shaped, upward and outward",
    size: "Large",
    conservationStatus: "Common",
    traits: ["Strong build", "Fast gait", "Excellent draft power"],
    description:
      "Kankrej is one of India's heaviest and most powerful draft breeds, originating from the Rann of Kutch area in Gujarat. Known for their unique lyre-shaped horns and distinctive silvery-grey coat, they are exceptional field workers capable of sustained heavy labor in extreme heat.",
  },
  {
    id: "ongole",
    name: "Ongole",
    hindiName: "ओंगोल",
    species: "Cattle",
    state: "Andhra Pradesh",
    purpose: "Draft",
    milkYield: "2-4 liters/day",
    bodyColor: "White to grey-white",
    hornType: "Short, thick at base",
    size: "Very large",
    conservationStatus: "Common",
    traits: ["Massive frame", "Tick resistant", "Disease hardy"],
    description:
      "Ongole cattle from coastal Andhra Pradesh are among the world's largest zebu cattle, renowned for their massive muscular frame and exceptional draft capacity. This breed's genetics have been used to develop the American Brahman breed and are highly valued globally for beef crossbreeding.",
  },
  {
    id: "hallikar",
    name: "Hallikar",
    hindiName: "हल्लीकर",
    species: "Cattle",
    state: "Karnataka",
    purpose: "Draft",
    milkYield: "1-3 liters/day",
    bodyColor: "Grey to dark grey",
    hornType: "Long, tapering to fine point",
    size: "Medium",
    conservationStatus: "Vulnerable",
    traits: ["Fast gait", "Agile", "Endurance over long distances"],
    description:
      "Hallikar cattle from Karnataka's Mysore region are prized for their incredible speed and endurance. Historically used in races and for transportation, their fine-boned structure and elegant build belie their tremendous stamina. Traditional farmers prize them for plowing terraced hillside fields.",
  },
  {
    id: "hariana",
    name: "Hariana",
    hindiName: "हरियाणा",
    species: "Cattle",
    state: "Haryana",
    purpose: "Dual Purpose",
    milkYield: "5-8 liters/day",
    bodyColor: "White",
    hornType: "Short, slightly curved upward",
    size: "Medium-large",
    conservationStatus: "Common",
    traits: ["Good milk yield", "Strong draft", "Hardy in varied climates"],
    description:
      "Hariana cattle are the pride of Haryana state, serving equally well as dairy animals and draft animals. Their white coat and moderate build make them versatile farm animals suited to the north Indian plains. They have historically formed the backbone of agricultural operations in the Indo-Gangetic plains.",
  },
  {
    id: "deoni",
    name: "Deoni",
    hindiName: "देओनी",
    species: "Cattle",
    state: "Maharashtra",
    purpose: "Dual Purpose",
    milkYield: "4-7 liters/day",
    bodyColor: "Black and white patches",
    hornType: "Medium length, curve outward",
    size: "Medium-large",
    conservationStatus: "Vulnerable",
    traits: ["Good milk fat", "Docile", "Adaptable to Deccan plateau"],
    description:
      "Deoni cattle from Maharashtra's Latur and Osmanabad districts are distinguished by their striking black-and-white patched coat. They are well-adapted to the harsh conditions of the Deccan plateau and produce milk with good fat content, making them valuable dual-purpose animals for local farmers.",
  },
  {
    id: "khillari",
    name: "Khillari",
    hindiName: "खिल्लारी",
    species: "Cattle",
    state: "Maharashtra",
    purpose: "Draft",
    milkYield: "1-2 liters/day",
    bodyColor: "Grey with darker points",
    hornType: "Long, swept back with fine points",
    size: "Compact-medium",
    conservationStatus: "Vulnerable",
    traits: ["Compact build", "Agile on hills", "Enduring"],
    description:
      "Khillari cattle from the Satara and Sholapur regions of Maharashtra are celebrated for their compact, muscular build and agility on uneven terrain. Traditionally used for heavy agricultural work in hilly regions, they are known for their fiery temperament and remarkable endurance.",
  },
  {
    id: "amrit-mahal",
    name: "Amrit Mahal",
    hindiName: "अमृत महल",
    species: "Cattle",
    state: "Karnataka",
    purpose: "Draft",
    milkYield: "1-2 liters/day",
    bodyColor: "Dark grey to black, white markings on face",
    hornType: "Long, curve forward then upward",
    size: "Medium",
    conservationStatus: "Vulnerable",
    traits: ["Military heritage", "Exceptional endurance", "Hardy"],
    description:
      "Amrit Mahal, meaning 'Dairy Department' in Kannada, was historically bred by the Mysore royal family as a military supply breed. These cattle were used to transport military supplies during Hyder Ali and Tipu Sultan's campaigns. Their legendary endurance and speed made them invaluable war cattle.",
  },
  {
    id: "punganur",
    name: "Punganur",
    hindiName: "पुंगनूर",
    species: "Cattle",
    state: "Andhra Pradesh",
    purpose: "Dairy",
    milkYield: "3-5 liters/day",
    bodyColor: "White, red, or brown",
    hornType: "Short, curved",
    size: "Very small (world's smallest)",
    conservationStatus: "Endangered",
    traits: ["World's smallest cattle", "High fat milk", "Low maintenance"],
    description:
      "Punganur cattle hold the distinction of being among the world's smallest cattle breeds, standing only 70-90 cm tall. Despite their tiny size, they produce milk with exceptionally high fat content (8%). Native to Chittoor district of Andhra Pradesh, their population has dwindled critically and intensive conservation efforts are underway.",
  },
  {
    id: "vechur",
    name: "Vechur",
    hindiName: "वेचुर",
    species: "Cattle",
    state: "Kerala",
    purpose: "Dairy",
    milkYield: "2-3 liters/day",
    bodyColor: "Various — black, brown, fawn",
    hornType: "Short",
    size: "Miniature (smallest zebu)",
    conservationStatus: "Endangered",
    traits: ["Smallest zebu breed", "High milk fat", "Disease resistant"],
    description:
      "Vechur cattle hold the Guinness World Record as the world's smallest cattle breed by average body weight. Native to the Vechur village in Kerala's Kottayam district, they nearly went extinct but were saved through dedicated conservation. Their milk contains medicinal properties recognized in Ayurveda.",
  },
  {
    id: "kangayam",
    name: "Kangayam",
    hindiName: "कंगायम",
    species: "Cattle",
    state: "Tamil Nadu",
    purpose: "Draft",
    milkYield: "2-3 liters/day",
    bodyColor: "Grey to white-grey",
    hornType: "Spreading upwards and outwards",
    size: "Medium",
    conservationStatus: "Vulnerable",
    traits: ["Good draft animal", "Hardy", "Adapted to Deccan conditions"],
    description:
      "Kangayam cattle from Erode district of Tamil Nadu are prized draft animals, traditionally used in the cotton and sugarcane fields of the Kongu region. Their moderate size and hardy constitution make them efficient workers in the hot dry conditions of the Tamil Nadu plains.",
  },
  {
    id: "bargur",
    name: "Bargur",
    hindiName: "बरगूर",
    species: "Cattle",
    state: "Tamil Nadu",
    purpose: "Draft",
    milkYield: "1-2 liters/day",
    bodyColor: "Brown with white markings",
    hornType: "Short, curved inward",
    size: "Small-medium",
    conservationStatus: "Endangered",
    traits: ["Hill breed", "Sure-footed", "Forest forager"],
    description:
      "Bargur cattle are a rare hill breed from the Bargur hills in Erode district of Tamil Nadu, bordering Karnataka. Adapted to steep forested terrain, they are sure-footed and capable of navigating narrow hill paths that other cattle cannot. Their numbers have fallen drastically due to forest restrictions and changing farming practices.",
  },
  {
    id: "murrah",
    name: "Murrah",
    hindiName: "मुर्रा",
    species: "Buffalo",
    state: "Haryana",
    purpose: "Dairy",
    milkYield: "15-25 liters/day",
    bodyColor: "Jet black",
    hornType: "Tightly coiled, clock-spring shape",
    size: "Large",
    conservationStatus: "Common",
    traits: ["Highest milk yield", "Rich fat content", "Top dairy buffalo"],
    description:
      "Murrah is India's premier dairy buffalo breed and arguably the world's highest milk-producing buffalo. Originating from Rohtak and Hisar districts of Haryana, their milk contains 7-7.5% fat. Their distinctive coiled horns are immediately recognizable. Murrah genetics have been used to improve buffalo breeds globally.",
  },
  {
    id: "surti",
    name: "Surti",
    hindiName: "सूरती",
    species: "Buffalo",
    state: "Gujarat",
    purpose: "Dairy",
    milkYield: "8-12 liters/day",
    bodyColor: "Rust to silver-grey",
    hornType: "Sickle-shaped, flat and curved",
    size: "Medium",
    conservationStatus: "Vulnerable",
    traits: ["Good milk quality", "Adaptable", "Moderate size"],
    description:
      "Surti buffalo from Gujarat's Charotar region are valued for their milk with 7-8% fat content. Their distinctive sickle-shaped horns and rust-colored coat distinguish them from other breeds. Well-adapted to Gujarat's coastal and agricultural environments, they are efficient producers on moderate feed.",
  },
  {
    id: "jaffarabadi",
    name: "Jaffarabadi",
    hindiName: "जाफराबादी",
    species: "Buffalo",
    state: "Gujarat",
    purpose: "Dairy",
    milkYield: "10-15 liters/day",
    bodyColor: "Black",
    hornType: "Heavy, drooping to cheek level",
    size: "Very large (heaviest buffalo)",
    conservationStatus: "Vulnerable",
    traits: ["Heaviest buffalo breed", "High milk yield", "Massive frame"],
    description:
      "Jaffarabadi buffalo from Gir forest area of Gujarat are the heaviest buffalo breed in the world, with bulls weighing up to 1200 kg. Their massive frame and heavy drooping horns make them instantly recognizable. Despite their size, they are productive dairy animals with good milk fat content.",
  },
  {
    id: "bhadawari",
    name: "Bhadawari",
    hindiName: "भदावरी",
    species: "Buffalo",
    state: "Uttar Pradesh",
    purpose: "Dairy",
    milkYield: "5-8 liters/day",
    bodyColor: "Copper-brown to dark",
    hornType: "Flat, curved backward",
    size: "Medium-small",
    conservationStatus: "Vulnerable",
    traits: ["Highest fat milk (13%)", "Drought resistant", "Economic feed conversion"],
    description:
      "Bhadawari buffalo from the Etawah and Agra districts of Uttar Pradesh produce milk with the highest fat content of any buffalo breed — up to 13% butter fat. Though their milk yield is moderate, the exceptional richness makes this milk extremely valuable for ghee production. They are adapted to sparse grazing conditions.",
  },
  {
    id: "nili-ravi",
    name: "Nili-Ravi",
    hindiName: "नीली-रावी",
    species: "Buffalo",
    state: "Punjab",
    purpose: "Dairy",
    milkYield: "12-18 liters/day",
    bodyColor: "Black with white markings on face, feet, tail",
    hornType: "Tightly coiled like Murrah",
    size: "Large",
    conservationStatus: "Common",
    traits: ["High milk yield", "White markings distinctive", "Hardy"],
    description:
      "Nili-Ravi buffalo originate from the Sutlej river valleys of Pakistan's Punjab but are widely distributed in Indian Punjab as well. Distinguished by distinctive white markings on the forehead, nose, feet, and tail switch against jet black coat. Second only to Murrah in milk production among Indian buffalo breeds.",
  },
  {
    id: "pandharpuri",
    name: "Pandharpuri",
    hindiName: "पंढरपुरी",
    species: "Buffalo",
    state: "Maharashtra",
    purpose: "Dairy",
    milkYield: "6-10 liters/day",
    bodyColor: "Black",
    hornType: "Very long, flat, sword-shaped",
    size: "Large",
    conservationStatus: "Vulnerable",
    traits: ["Longest horns of any buffalo", "Good milk yield", "Sacred status"],
    description:
      "Pandharpuri buffalo from Solapur district of Maharashtra are distinguished by their extraordinarily long, flat sword-shaped horns — the longest of any buffalo breed. They hold special significance in the Pandharpur temple town where they have been bred for centuries. Despite their impressive horns, they are gentle and productive dairy animals.",
  },
  {
    id: "nagpuri",
    name: "Nagpuri",
    hindiName: "नागपुरी",
    species: "Buffalo",
    state: "Maharashtra",
    purpose: "Draft",
    milkYield: "3-5 liters/day",
    bodyColor: "Black, white markings on forehead and legs",
    hornType: "Long, flat, curved back",
    size: "Large",
    conservationStatus: "Common",
    traits: ["Good draft capacity", "White markings", "Hardy in Vidarbha heat"],
    description:
      "Nagpuri buffalo from the Vidarbha region of Maharashtra are primarily used for draft work in the cotton fields of central India. Their white leg markings and forehead blaze are characteristic features. Well-adapted to the extreme heat of the Vidarbha region, they are valued working animals in this agricultural zone.",
  },
  {
    id: "toda",
    name: "Toda",
    hindiName: "टोडा",
    species: "Buffalo",
    state: "Tamil Nadu",
    purpose: "Dairy",
    milkYield: "3-4 liters/day",
    bodyColor: "Dark brown",
    hornType: "Spreading, crescent-shaped",
    size: "Large",
    conservationStatus: "Endangered",
    traits: ["Tribal breed", "Nilgiri highlands", "Sacred to Toda tribe"],
    description:
      "Toda buffalo are inseparably linked with the Toda tribal community of the Nilgiri hills in Tamil Nadu. These buffalo hold profound spiritual and cultural significance in Toda society, featuring prominently in their mythology, rituals, and economy. Adapted to high-altitude grasslands, their conservation is tied to preserving Toda culture.",
  },
  {
    id: "mehsana",
    name: "Mehsana",
    hindiName: "मेहसाणा",
    species: "Buffalo",
    state: "Gujarat",
    purpose: "Dairy",
    milkYield: "10-15 liters/day",
    bodyColor: "Black to brown-black",
    hornType: "Less coiled than Murrah, somewhat flat",
    size: "Large",
    conservationStatus: "Common",
    traits: ["Murrah-Surti cross", "Good milk yield", "Adaptable"],
    description:
      "Mehsana buffalo is a stabilized crossbreed developed from Murrah and Surti buffalo in Gujarat's Mehsana district. They combine the high milk yield of Murrah with the adaptability of Surti. Their less tightly coiled horns distinguish them from pure Murrah. They have become one of Gujarat's most commercially important dairy animals.",
  },
  {
    id: "marathwadi",
    name: "Marathwadi",
    hindiName: "मराठवाडी",
    species: "Buffalo",
    state: "Maharashtra",
    purpose: "Dual Purpose",
    milkYield: "4-6 liters/day",
    bodyColor: "Black",
    hornType: "Curved, moderate length",
    size: "Medium",
    conservationStatus: "Vulnerable",
    traits: ["Dual purpose", "Drought resistant", "Marathwada plateau adapted"],
    description:
      "Marathwadi buffalo from Maharashtra's drought-prone Marathwada region have evolved to survive on sparse vegetation and scarce water. Their dual-purpose nature — providing both milk and draft power — makes them essential to subsistence farming families in this challenging agricultural region where single-purpose animals are a luxury.",
  },
];

export const getBreedById = (id: string): Breed | undefined => {
  return breedsData.find((b) => b.id === id);
};

export const filterBreeds = (
  species?: string,
  purpose?: string,
  conservationStatus?: string,
): Breed[] => {
  return breedsData.filter((b) => {
    if (species && b.species !== species) return false;
    if (purpose && b.purpose !== purpose) return false;
    if (conservationStatus && b.conservationStatus !== conservationStatus)
      return false;
    return true;
  });
};
